app:
    performance-trace: false # включить / выключить трассировку производительности методов помеченных @PerformanceTracing
    dbpersist:
        batch-size: 500 # количество запросов, одновременно пишущихся в базу
        delay: 500 # период срабатывания таймера для записи в базу (мс)
    thread: # экспериментировал с разными значениями, сильного влияния на производительность не ощутил
        core-pool-size: 10
        max-pool-size: 100
        keep-alive-seconds: 5
        queue-capacity: 10000

spring:
   data:
      mongodb: # настройки монги
        host: localhost
        port: 27017
        uri: mongodb://localhost/search_requests
        username:
        password:

server:
    tomcat:
        max-threads: 500
