app:
    store:
        implementation: concurrentQueue
    dbpersist:
        batch-size: 500
        delay: 500
    thread:
        core-pool-size: 10
        max-pool-size: 100
        keep-alive-seconds: 5
        queue-capacity: 10000

spring:
   data:
      mongodb:
        host: localhost
        port: 27017
        uri: mongodb://localhost/search_requests
        username:
        password:

server:
    tomcat:
        max-threads: 500
